import { SEMANTIC_TOKENS } from '@dsg/contracts';
import type { ResolvedDesignSystem, ThemeMode } from '../resolve.js';
import {
  colorDeclarations,
  colorVar,
  declaration,
  radiusDeclarations,
  section,
  semanticVar,
  shadowDeclarations,
  typographyDeclarations,
} from './naming.js';

/**
 * Framework-agnostic primitives. This is the alternative to theme.css for projects not using
 * Tailwind — not a layer beneath it. The named spacing steps exist here because plain CSS
 * cannot derive multiples from a base the way Tailwind's utilities can.
 */
export function emitTokensCss(resolved: ResolvedDesignSystem): string {
  return [
    '/* Generated by Design System Generator — edit the system, not this file. */',
    '',
    ':root {',
    ...section('Color scales', colorDeclarations(resolved)),
    ...section('Typography', typographyDeclarations(resolved)),
    ...section('Spacing', [
      declaration('--spacing', `${resolved.spacing.baseRem}rem`),
      ...resolved.spacing.tokens.map((token) =>
        declaration(`--spacing-${token.name}`, `${token.rem}rem`),
      ),
    ]),
    ...section('Radii', radiusDeclarations(resolved)),
    ...section('Shadows', shadowDeclarations(resolved)),
    '}',
    '',
  ].join('\n');
}

function semanticBlock(resolved: ResolvedDesignSystem, mode: ThemeMode): string[] {
  return SEMANTIC_TOKENS.map((token) => {
    const { ref } = resolved.semantic[mode][token];
    return declaration(semanticVar(token), `var(${colorVar(ref.palette, ref.step)})`);
  });
}

/** Semantic aliases over the primitives in tokens.css. Import that file first. */
export function emitSemanticCss(resolved: ResolvedDesignSystem): string {
  return [
    '/* Generated by Design System Generator — edit the system, not this file. */',
    '/* Requires tokens.css. */',
    '',
    ':root {',
    ...semanticBlock(resolved, 'light'),
    '}',
    '',
    ".dark,\n[data-theme='dark'] {",
    ...semanticBlock(resolved, 'dark'),
    '}',
    '',
  ].join('\n');
}
