import { SEMANTIC_TOKENS } from '@dsg/contracts';
import type { ResolvedDesignSystem } from '../resolve.js';

export function emitReadme(systemName: string, resolved: ResolvedDesignSystem): string {
  const paletteNames = resolved.palettes.map((palette) => palette.name);
  const textSteps = resolved.typography.steps.map((step) => step.name);

  return `# ${systemName}

Generated by Design System Generator. These files are output, not source — regenerate them
from the editor rather than editing them by hand.

## Pick one setup

\`theme.css\` and \`tokens.css\` + \`semantic.css\` are **alternatives**, not layers. Both define the
same custom properties, so a component written against \`var(--color-background)\` works either way.

### Tailwind v4

\`theme.css\` is a complete entry point — it already imports Tailwind.

\`\`\`ts
// main.ts / main.tsx
import './theme.css';
\`\`\`

You get utilities for every token: \`bg-${paletteNames[0] ?? 'brand'}-500\`, \`text-lg\`, \`rounded-md\`,
\`shadow-md\`, \`p-4\`, plus semantic utilities like \`bg-background\` and \`text-foreground\`.

### Plain CSS

\`\`\`css
@import './tokens.css';
@import './semantic.css';
\`\`\`

## Dark mode

Dark mode is driven by a \`.dark\` class or \`[data-theme="dark"]\` on a wrapping element (usually
\`<html>\`), so your app decides when it applies. To follow the OS preference, set it once on load:

\`\`\`ts
const prefersDark = matchMedia('(prefers-color-scheme: dark)');
const apply = () => document.documentElement.classList.toggle('dark', prefersDark.matches);
apply();
prefersDark.addEventListener('change', apply);
\`\`\`

Swap \`prefersDark.matches\` for your own stored preference to give users an explicit toggle.

## What's in here

| File | Contents |
| --- | --- |
| \`theme.css\` | Tailwind v4 entry: imports Tailwind, defines every token, wires dark mode |
| \`tokens.css\` | Primitive scales as plain custom properties |
| \`semantic.css\` | Semantic aliases over \`tokens.css\`, including dark overrides |

**Palettes** — ${paletteNames.map((name) => `\`${name}\``).join(', ')}, each with steps
50, 100, 200 … 900, 950.

**Type scale** — ${textSteps.map((name) => `\`${name}\``).join(', ')}. Each carries a matching
line-height and letter-spacing.

**Semantic colors** — ${SEMANTIC_TOKENS.map((token) => `\`${token}\``).join(', ')}.
`;
}
