import { SEMANTIC_TOKENS } from '@dsg/contracts';
import type { ResolvedDesignSystem, ThemeMode } from '../resolve.js';
import {
  colorDeclarations,
  colorVar,
  declaration,
  radiusDeclarations,
  section,
  semanticSourceVar,
  semanticVar,
  shadowDeclarations,
  typographyDeclarations,
} from './naming.js';

function semanticSourceBlock(resolved: ResolvedDesignSystem, mode: ThemeMode): string[] {
  return SEMANTIC_TOKENS.map((token) => {
    const { ref } = resolved.semantic[mode][token];
    return declaration(semanticSourceVar(token), `var(${colorVar(ref.palette, ref.step)})`);
  });
}

/**
 * Self-contained Tailwind v4 entry point. Emits primitives as real theme values (so
 * `bg-brand-500` and `text-lg` exist) and semantic colors as `inline` aliases pointing at a
 * separate variable layer (so `bg-background` follows the active theme at runtime rather
 * than being frozen at build time).
 */
export function emitTailwindTheme(resolved: ResolvedDesignSystem): string {
  const lines = [
    '/* Generated by Design System Generator — edit the system, not this file. */',
    '',
    "@import 'tailwindcss';",
    '',
    '/* Dark mode is driven by a class or data attribute so the app stays in control. To',
    '   follow the OS instead, see the snippet in README.md. */',
    "@custom-variant dark (&:where(.dark, .dark *, [data-theme='dark'], [data-theme='dark'] *));",
    '',
    '/* `static` forces every variable to be emitted. Without it Tailwind drops theme values',
    '   no utility references, and the semantic layer below reaches them only through var(). */',
    '@theme static {',
    ...section('Color scales', colorDeclarations(resolved)),
    ...section('Typography', typographyDeclarations(resolved)),
    ...section('Spacing — Tailwind derives every step from this base', [
      declaration('--spacing', `${resolved.spacing.baseRem}rem`),
    ]),
    ...section('Radii', radiusDeclarations(resolved)),
    ...section('Shadows', shadowDeclarations(resolved)),
    '}',
    '',
    '/* `inline` keeps utilities pointing at the variable instead of copying its value, which',
    '   is what makes runtime theme switching work. */',
    '@theme inline {',
    ...SEMANTIC_TOKENS.map((token) =>
      declaration(semanticVar(token), `var(${semanticSourceVar(token)})`),
    ),
    '}',
    '',
    ':root {',
    ...semanticSourceBlock(resolved, 'light'),
    '}',
    '',
    ".dark,\n[data-theme='dark'] {",
    ...semanticSourceBlock(resolved, 'dark'),
    '}',
    '',
  ];

  return lines.join('\n');
}
